### ISSUE TITLE
Activity instance will become null when switching between Activities

### ISSUE THREAD

**Issue by am5a03** [afollestad/assent#1]
Hi, it looks like there's a bug in the setup:

```java
@Override
protected void onStop() {
        // Cleans up references of the Activity to avoid memory leaks
        Assent.setActivity(null);
        super.onStop();
}
```
For example, I am in Activity A, and when I start Activity B, the last onStop() call in A will clear the Activity instance held in Assent
```
A: onCreate()
A: onStart()
B: onCreate()
B: onStart()
A: onStop()
```

**Comment by afollestad** [comment]
https://github.com/afollestad/assent/releases/tag/0.1.1

**Comment by afollestad** [comment]
0.1.2 is out now
