### ISSUE TITLE
Detect "denied permanently" permissions

### ISSUE THREAD

**Issue by guger** [afollestad/assent#10]
Implement a 'shouldShowRequestPermissionRationale' callback and a information, if the user ticked the 'Never ask again'-option.

**Comment by afollestad** [comment]
Rationales before requests, I can do - there is no API to detect "never ask again", though.

**Comment by guger** [comment]
Have a look at this question:
https://stackoverflow.com/a/51514740/5994190

Perhaps this is a way to detect, whether a permission was permanently denied or not!

**Comment by guger** [comment]
Actually "Dexter" is providing such an information, so it should be possible to determine whether it is permanently denied or not.

**Comment by guger** [comment]
Dexter implements it like described in the stackoverflow post:
https://github.com/Karumi/Dexter/blob/master/dexter/src/main/java/com/karumi/dexter/DexterInstance.java (line 254).

**Comment by guger** [comment]
Any updates?
Plans to implement it?
Shall I try to implement it?

**Comment by afollestad** [comment]
It's already implemented and in th codebase. Just haven't finalized the API.

**Comment by guger** [comment]
The ```isPermanentlyDenied``` feature, too?

**Comment by afollestad** [comment]
No, not yet.

**Comment by thedukerchip** [comment]
Hey @afollestad, Is detecting **permantely denied permissions** feature added?
