### ISSUE TITLE
Issue with runWithPermissions / permanently denied in 3.0 RC3

### ISSUE THREAD

**Issue by cfsbhawkins** [afollestad/assent#16]
I think you have an issue with the permanently denied permissions check, I am using the runWithPermissions helper with my camera, if one denies it the first time, then clicks the camera button again, they get asked to accept. When they do, the camera never launches. Putting the debugger on the isAllGranted call of the runWithPermissions, it says camera is Permanently Denied, even though if you go and look at the app under app settings its set to allow.

**Comment by afollestad** [comment]
I consistently get the correct behavior when testing this from the sample project.

**Comment by afollestad** [comment]
Wait nevermind I see it now
