### ISSUE TITLE
System Alert Window Permission is missing

### ISSUE THREAD

**Issue by adnbsr** [afollestad/assent#2]
SYSTEM_ALERT_WINDOW  permission is needed

**Comment by afollestad** [comment]
You can still pass the actual constants from PackageManager.

**Comment by adnbsr** [comment]
Yep, I did as you said, but it will help others to get rid of time consumption :)

**Comment by afaucogney** [comment]
VIBRATE permission is also missing

**Comment by afollestad** [comment]
@afaucogney no it's not, that's not a permission that requires a request.

**Comment by afollestad** [comment]
http://developer.android.com/guide/topics/security/permissions.html#normal-dangerous
