### ISSUE TITLE
Rationale message

### ISSUE THREAD

**Issue by hisankaran** [afollestad/assent#4]
Hi,

Thanks for the convenience library. I am thinking is it possible to show [rationale](https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldShowRequestPermissionRationale%28android.app.Activity,%28java.lang.String%29) message when required?

**Comment by afollestad** [comment]
The newer Google design guidelines no longer include rationale messages, but instead give examples of other UIs that your app could use for this sort of thing.

https://material.io/design/platform-guidance/android-permissions.html
