### ISSUE TITLE
Retry for Permission Failed if User Once Declined the permission.

### ISSUE THREAD

**Issue by rasheedk** [afollestad/assent#7]
###### Include the following:
 - Library version: `0.2.5`
 - Device OS version: `8.0`
 - Device Manufacturer: `OnePlus `
 - Device Name: `One Plus 5`

I am using this code inside a fragment

```  
 Assent.setFragment(this, this);
        if (!Assent.isPermissionGranted(Assent.READ_EXTERNAL_STORAGE)) {
            Assent.requestPermissions(new AssentCallback() {
                @Override
                public void onPermissionResult(PermissionResultSet result) {
                    // Permission granted or denied

                }
            }, 27, Assent.READ_EXTERNAL_STORAGE);
        }
```
 
###### Reproduction Steps

1. Decline a permission for read external storage permission.
2. call the method which request the permission
3. Permission dialogue will not be called: 

###### Expected Result
It should show again the dialogue. Also i am not getting the permission result here

###### Actual Result
Permission dialogue will not be shown

**Comment by afollestad** [comment]
The library was rebuilt with version 1.0.0 and this should no longer be a problem.
